# SiGen Plant Sensor: sensor.sigen_plant_battery_state_of_charge
sigen_plant_battery_state_of_charge:
  command_line:
    - sensor:
        unique_id: "sensor.sigen_plant_battery_state_of_charge"
        name: "Sigen Plant Battery State of Charge"
        command: "python3 config/transform_sensor.py config/packages/sigen/sigen_plant_battery_state_of_charge.json passthrough"
        value_template: "{{ value_json.state }}"
        json_attributes_path: "$.attributes"
        json_attributes:
          - state_class
          - unit_of_measurement
          - device_class
          - icon
          - friendly_name
        scan_interval: 3600
