# SiGen Plant Sensor: sensor.sigen_plant_max_active_power
sigen_plant_max_active_power:
  command_line:
    - sensor:
        unique_id: "sensor.sigen_plant_max_active_power"
        name: "Sigen Plant Max Active Power"
        command: "python3 config/transform_sensor.py config/packages/sigen/sigen_plant_max_active_power.json passthrough"
        value_template: "{{ value_json.state }}"
        json_attributes_path: "$.attributes"
        json_attributes:
          - state_class
          - unit_of_measurement
          - device_class
          - friendly_name
        scan_interval: 3600
