# SiGen Plant Sensor: sensor.sigen_plant_rated_energy_capacity
sigen_plant_rated_energy_capacity:
  command_line:
    - sensor:
        unique_id: "sensor.sigen_plant_rated_energy_capacity"
        name: "Sigen Plant Rated Energy Capacity"
        command: "python3 config/transform_sensor.py config/packages/sigen/sigen_plant_rated_energy_capacity.json passthrough"
        value_template: "{{ value_json.state }}"
        json_attributes_path: "$.attributes"
        json_attributes:
          - state_class
          - unit_of_measurement
          - device_class
          - friendly_name
        scan_interval: 3600
