# Solar Forecast Sensor: sensor.energy_production_d6_east (Day 6)
energy_production_d6_east:
  command_line:
    - sensor:
        unique_id: "sensor.energy_production_d6_east"
        name: "East solar production forecast Estimated energy production - 6 days from now"
        command: "python3 config/transform_sensor.py config/packages/open_meteo_solar_forecast/energy_production_d6_east.json day_offset --day-offset 6"
        value_template: "{{ value_json.state }}"
        json_attributes_path: "$.attributes"
        json_attributes:
          - watts
          - wh_period
          - unit_of_measurement
          - device_class
          - friendly_name
        scan_interval: 3600
