# Solar Forecast Sensor: sensor.energy_production_tomorrow_south (Day 1)
energy_production_tomorrow_south:
  command_line:
    - sensor:
        unique_id: "sensor.energy_production_tomorrow_south"
        name: "South solar prediction forecast Estimated energy production - tomorrow"
        command: "python3 config/transform_sensor.py config/packages/open_meteo_solar_forecast/energy_production_tomorrow_south.json day_offset --day-offset 1"
        value_template: "{{ value_json.state }}"
        json_attributes_path: "$.attributes"
        json_attributes:
          - watts
          - wh_period
          - unit_of_measurement
          - device_class
          - friendly_name
        scan_interval: 3600
